[package]
name = "iota-streams-core"
version = "0.1.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "core"]
description = "A rust implementation of the IOTA Streams core utils"

[lib]
name = "iota_streams_core"
path = "src/lib.rs"

[dependencies]
rand = "0.7"
serde = "1.0.110"

[dev-dependencies]
criterion = "0.3"

[features]

# Enable traversal Merkle tree implementation for MSS private key.
# By default a complete Merkle tree implementation is used.
mss_merkle_tree_traversal = []

[[bench]]
name = "troika"
harness = false

[[bench]]
name = "ftroika"
harness = false
